<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Includes -->
  <xacro:include filename="wheels.xacro" />

  <!-- Variables -->
  <xacro:property name="base_mass" value="3.214" /> <!-- kg -->
  <xacro:property name="base_side_length" value="1.05" /> <!-- m -->
  <xacro:property name="base_clearance" value="0.048" /> <!-- m -->
  <xacro:property name="wheel_radius" value="0.076" /> <!-- m -->
  <xacro:property name="shaft_length" value="0.05" /> <!-- m -->
  <xacro:property name="corner_side_length" value="0.15" /> <!-- m -->
  <xacro:property name="rod_width" value="0.02" /> <!-- m -->
  <xacro:property name="chassis_offset" value="0.01" /> <!-- m -->
  <xacro:property name="encoder_radius" value="0.05" /> <!-- m -->
  <xacro:property name="encoder_scale" value="${100/152}" /> <!-- m -->

  <!-- Derived Vars -->
  <xacro:property name="base_height" value="${1.732 * base_side_length / 2}" /> <!-- m -->

  <!-- Base Link -->
  <joint name="base_joint" type="fixed">
    <parent link="base_link" />
    <child link="body_link" />
  </joint>
  <link name="base_link" />

  <!-- Base Footprint -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin rpy="0.0 0.0 ${pi/2}"/>
  </joint>
  <link name="base_footprint" />

  <!-- Base -->
  <link name="body_link">
    <visual>
      <origin xyz="0.0 -${base_height/3} ${base_clearance - chassis_offset}" rpy="0.0 0.0 ${pi/6}" />
      <geometry>
        <mesh filename="file://$(find omni_bot_sim)/description/meshes/chassis.stl" />
      </geometry>
      <material name="light_gray">
        <color rgba="0.75 0.75 0.75 1.0" />
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 -${base_height/3} ${base_clearance}" rpy="0.0 0.0 ${pi/6}" />
      <geometry>
        <mesh filename="file://$(find omni_bot_sim)/description/meshes/bot_base.stl" />
      </geometry>
    </collision>
    <inertial>
      <!-- <origin xyz="0.0 ${-base_height/3} ${base_clearance}" rpy="0.0 0.0 ${pi/6}"/> -->
      <origin xyz="0.0 0.0 ${base_clearance}" rpy="0.0 0.0 0.0" />
      <mass value="${base_mass}" />
      <inertia ixx="0.1798003"
        ixy="0.0024346"
        ixz="-0.0001306"
        iyy="0.1827598"
        iyz="-0.0002425"
        izz="0.3538762" />
    </inertial>
  </link>
  <gazebo reference="body_link">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- Wheels -->
  <xacro:wheel pos="front" parent="base_link">
    <origin
      xyz="0.0 ${2 * base_height / 3 - (1.732 * corner_side_length / 2) - (rod_width / 2) - shaft_length} ${wheel_radius}"
      rpy="${pi/2} 0.0 0.0" />
  </xacro:wheel>
  <xacro:wheel pos="left" parent="base_link">
    <origin
      xyz="-${((2 * base_height / 3) - (1.732 * corner_side_length / 2) - (rod_width / 2) - shaft_length)* cos(pi/6)} -${((2 * base_height / 3) - (1.732 * corner_side_length / 2) - (rod_width / 2) - shaft_length) * sin(pi/6)} ${wheel_radius}"
      rpy="${pi/2} 0.0 ${pi/6 + pi/2}" />
  </xacro:wheel>
  <xacro:wheel pos="right" parent="base_link">
    <origin
      xyz="${((2 * base_height / 3) - (1.732 * corner_side_length / 2) - (rod_width / 2) - shaft_length)* cos(pi/6)} -${((2 * base_height / 3) - (1.732 * corner_side_length / 2) - (rod_width / 2) - shaft_length) * sin(pi/6)} ${wheel_radius}"
      rpy="${pi/2} 0.0 -${pi/6 + pi/2}" />
  </xacro:wheel>

  <!-- Encoders -->
  <xacro:encoder pos="X" parent="base_link" scale="${encoder_scale}">
    <origin xyz="0.0 0.08 ${encoder_radius}" rpy="-${pi/2} 0.0 0.0" />  <!-- 0.09 is experimental
    value -->
  </xacro:encoder>
  <xacro:encoder pos="Y" parent="base_link" scale="${encoder_scale}">
    <origin xyz="-0.04 -0.04 ${encoder_radius}" rpy="0.0 -${pi/2} 0.0" /> <!-- 0.042 and 0.03 are
    experimental values -->
  </xacro:encoder>

  <!-- Lidar -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="lidar_link" />
    <origin xyz="0.0 0.0 0.15" rpy="0.0 0.0 ${pi}" />
  </joint>
  <link name="lidar_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <mesh filename="file://$(find omni_bot_sim)/description/meshes/Scanner.stl" />
      </geometry>
      <material name="dark_gray">
        <color rgba="0.25 0.25 0.25 1.0" />
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <mesh filename="file://$(find omni_bot_sim)/description/meshes/Scanner.stl" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <mass value="0.1" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>
  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
  </gazebo>

</robot>
